### ISSUE TITLE
Running `sync-ganeti-files.sh` in MSP causes No JSON object could be decoded error

### ISSUE THREAD

**Issue by gene1wood** [iocoop/iocoop-make-ganeti-vps#18]
I just went to tear down a VPS and ran sync-ganeti-files.sh and got these errors

```
root@g0-n00:~# /root/make-vps/bin/sync-ganeti-files.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
g0-n00.iocoop.org: Not copying files to myself
g0-n01.iocoop.org: syncing dir /etc/ganeti/
g0-n01.iocoop.org: syncing dir /root/make-vps/
g0-n01.iocoop.org: syncing dir /root/debs/
g0-n01.iocoop.org: syncing dir /home/vmconsole/.ssh/
g0-n01.iocoop.org: syncing dir /var/cache/ganeti-instance-image/
g0-n01.iocoop.org: syncing dir /home/iso/
g0-n01.iocoop.org: syncing file /etc/hosts
g0-n01.iocoop.org: syncing file /etc/sudoers
g0-n01.iocoop.org: syncing file /etc/default/ganeti-instance-debootstrap
g0-n01.iocoop.org: syncing file /etc/default/ganeti-instance-image
g0-n01.iocoop.org: syncing file /etc/make-vps.json
g0-n02.iocoop.org: syncing dir /etc/ganeti/
g0-n02.iocoop.org: syncing dir /root/make-vps/
g0-n02.iocoop.org: syncing dir /root/debs/
g0-n02.iocoop.org: syncing dir /home/vmconsole/.ssh/
g0-n02.iocoop.org: syncing dir /var/cache/ganeti-instance-image/
g0-n02.iocoop.org: syncing dir /home/iso/
g0-n02.iocoop.org: syncing file /etc/hosts
g0-n02.iocoop.org: syncing file /etc/sudoers
g0-n02.iocoop.org: syncing file /etc/default/ganeti-instance-debootstrap
g0-n02.iocoop.org: syncing file /etc/default/ganeti-instance-image
g0-n02.iocoop.org: syncing file /etc/make-vps.json
```

**Comment by SuperQ** [comment]
Same problem as #19
