### ISSUE TITLE
Running `sync-auth-keys.sh` triggers No JSON object could be decoded error

### ISSUE THREAD

**Issue by gene1wood** [iocoop/iocoop-make-ganeti-vps#19]
```
root@g0-n00:~# /root/make-vps/bin/sync-auth-keys.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/root/bin/make-access-files.py", line 26, in <module>
    config = dict(defaults.items() + json.load(f).items())
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR: Failed to generate access files
```

**Comment by SuperQ** [comment]
This is because an "Ansible managed" comment was added to the file. This was fixed with https://github.com/iocoop/configs/pull/141, but it looks like someone may have re-deployed on an old checkout.

I re-deployed from master, which cleaned up the config file.
