### ISSUE TITLE
 VPS creation in SCL failing due to curl

### ISSUE THREAD

**Issue by gene1wood** [iocoop/iocoop-make-ganeti-vps#23]
Any idea why VPS creation is failing in SCL on g1-n03?

```
# /root/bin/make-vps.sh -n $newvpsname -s $numberofslices -o $os
INFO: SSH Key OK: coyote@whycoyoterunslinux.com
INFO: Creating vps
Instance name: vectorprime.whycoyoterunslinux.com
Shares: 1
  * Ram 1G
  * Disk 25G
Target IP: 216.252.162.194
Target vlan: virbr3005
Target netmask: 255.255.255.192 (/26)
Target gateway: 216.252.162.254
Target OS: debootstrap+bullseye
Create VPS (y/n)?y
Thu Jun  9 18:56:20 2022  - INFO: Selected nodes for instance vectorprime.whycoyoterunslinux.com via iallocator hail: g1-n01.iocoop.org
Thu Jun  9 18:56:20 2022 * disk 0, size 25.0G
Thu Jun  9 18:56:20 2022 * creating instance disks...
Thu Jun  9 18:56:21 2022 adding instance vectorprime.whycoyoterunslinux.com to cluster config
Thu Jun  9 18:56:21 2022 adding disks to cluster config
Thu Jun  9 18:56:21 2022 * running the instance OS create scripts...
Thu Jun  9 19:04:22 2022 Could not update metadata for instance 'vectorprime.whycoyoterunslinux.com': Error while executing backend function: Failed to start metadata daemon
INFO: Instance created
INFO: Activating disks
g1-n01.iocoop.org:disk/0:/dev/rbd2
INFO: Getting instance info from API
/root/make-vps/bin/vps-lib.sh: line 19: curl: command not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR: Invalid ostype
usage tweak-vps.sh -h -n <hostname>
  -n    The hostname for the instance (must resolve)
ERROR: Failed to tweak
```

Can't find curl?

```
# which curl
/usr/bin/curl
```

Seems to be there.

**Comment by gene1wood** [comment]
Looks like the cause is the `g1-n01` didn't have curl installed. I've installed it and will now try to see how to gracefully pick the VPS provisioning back up from where it failed.
